// Generates dark.css from the light stylesheets: every rule is scoped to
// :root[data-theme="dark"] and colours are remapped property-by-property.
const fs = require('fs'), postcss = require('postcss');
const SCOPE = ':root[data-theme="dark"]';

function parse(hex) {
  let h = hex.slice(1);
  if (h.length <= 4) h = [...h].map(c => c + c).join('');
  const n = i => parseInt(h.slice(i, i + 2), 16) / 255;
  return { r: n(0), g: n(2), b: n(4), a: h.length === 8 ? n(6) : 1 };
}
function toHsl({ r, g, b }) {
  const mx = Math.max(r, g, b), mn = Math.min(r, g, b), l = (mx + mn) / 2, d = mx - mn;
  let h = 0, s = 0;
  if (d) {
    s = l > .5 ? d / (2 - mx - mn) : d / (mx + mn);
    h = mx === r ? (g - b) / d + (g < b ? 6 : 0) : mx === g ? (b - r) / d + 2 : (r - g) / d + 4;
    h *= 60;
  }
  return { h, s, l };
}
function hslHex(h, s, l, a) {
  const f = n => { const k = (n + h / 30) % 12, x = s * Math.min(l, 1 - l); return l - x * Math.max(-1, Math.min(k - 3, 9 - k, 1)); };
  const x = v => Math.round(Math.max(0, Math.min(1, v)) * 255).toString(16).padStart(2, '0');
  return '#' + x(f(0)) + x(f(8)) + x(f(4)) + (a < 1 ? x(a) : '');
}
// role: 'bg' | 'text' | 'border' | 'other'
function map(hex, role) {
  const c = parse(hex); if (c.a < 1) return hex; // keep translucent colours
  const { h, s, l } = toHsl(c);
  const tint = Math.min(s, .35); // keep a hint of the brand hue in surfaces
  if (role === 'bg') {
    if (l > .985) return '#14141f';                          // white cards -> surface
    if (l > .8) return hslHex(250, tint * .6, .05 + (.975 - l) * 1.9 + .05, 1); // page/tints
    return hex;                                              // brand / already-dark fills
  }
  if (role === 'border') {
    if (l > .8) return hslHex(245, .18, .12 + (1 - l) * .9, 1);
    return hex;
  }
  if (role === 'text') {
    if (l < .3) return '#f2f2f8';
    if (l < .5) return s > .35 ? hslHex(h, Math.min(s, .9), .78, 1) : '#c7c7d9';
    if (l < .7) return s > .35 ? hslHex(h, Math.min(s, .8), .74, 1) : '#9d9db5';
    return hex;
  }
  return hex;
}
const role = p => /^background/.test(p) ? 'bg' : /^border|outline/.test(p) ? 'border' : (p === 'color' || p === 'fill' || p === 'stroke') ? 'text' : 'other';
const HEX = /#(?:[0-9a-fA-F]{8}|[0-9a-fA-F]{6}|[0-9a-fA-F]{3,4})\b/g;

function scope(sel) {
  return sel.split(',').map(s => {
    s = s.trim();
    if (/^:root\[data-theme="?dark"?\]/.test(s)) return s; // already dark-specific
    if (s === 'html' || s === ':root') return SCOPE;
    if (/^html\b/.test(s)) return s.replace(/^html/, SCOPE);
    if (s === 'body' || s === '*' || /^\*/.test(s)) return `${SCOPE} ${s}`;
    return `${SCOPE} ${s}`;
  }).join(',');
}

let out = '/* AUTO-GENERATED by tools/make-dark.js — do not edit by hand */\n';
for (const file of ['styles.css', 'studio.css']) {
  const root = postcss.parse(fs.readFileSync(file, 'utf8'));
  root.walkRules(rule => {
    if (rule.parent.type === 'atrule' && /keyframes/.test(rule.parent.name)) return;
    rule.selector = scope(rule.selector);
  });
  root.walkDecls(d => {
    if (d.parent.parent && d.parent.parent.type === 'atrule' && /keyframes/.test(d.parent.parent.name)) return;
    if (d.prop === 'box-shadow') return;
    const r = role(d.prop);
    if (r === 'other') return;
    d.value = d.value.replace(/\bwhite\b/gi, '#ffffff').replace(HEX, m => map(m, r));
  });
  // drop rules that changed nothing is not needed; keep the output simple
  out += root.toString() + '\n';
}
fs.writeFileSync('dark.css', out);
console.log('dark.css', out.length, 'bytes');
